<a href="https://colab.research.google.com/github/sanghavividhi/Natural-Language-Processing-NLP-/blob/main/Built-in_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
iris=load_iris()

df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['species']=pd.Categorical.from_codes(iris.target,iris.target_names)
df.head()

   sepal length (cm)  sepal width (cm)  ...  petal width (cm)  species
0                5.1               3.5  ...               0.2   setosa
1                4.9               3.0  ...               0.2   setosa
2                4.7               3.2  ...               0.2   setosa
3                4.6               3.1  ...               0.2   setosa
4                5.0               3.6  ...               0.2   setosa

[5 rows x 5 columns]

In [ ]:
print(df.shape)

(150, 5)

In [ ]:
x=df[iris.feature_names]
y=df['species']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)
print('Train Size:',x_train.shape)
print('Test Size:',x_test.shape)

Train Size: (120, 4)
Test Size: (30, 4)

In [ ]:
model=LogisticRegression(max_iter=200)
model.fit(x_train,y_train)

LogisticRegression(max_iter=200)

In [ ]:
y_pred=model.predict(x_test)
print('Accuracy :',accuracy_score(y_test,y_pred))

Accuracy : 0.9666666666666667

In [ ]:
print('Confusion Matrix :',confusion_matrix(y_test,y_pred))

Confusion Matrix : [[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]

In [ ]:
print('Classification Report :',classification_report(y_test,y_pred))

Classification Report :               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.90      0.95        10
   virginica       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

In [ ]:
# Task 1

import pandas as pd
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
digits=load_digits()
df=pd.DataFrame(digits.data,columns=digits.feature_names)
df['target']=digits.target
df.head()

   pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_6  pixel_7_7  target
0        0.0        0.0        5.0  ...        0.0        0.0       0
1        0.0        0.0        0.0  ...        0.0        0.0       1
2        0.0        0.0        0.0  ...        9.0        0.0       2
3        0.0        0.0        7.0  ...        0.0        0.0       3
4        0.0        0.0        0.0  ...        0.0        0.0       4

[5 rows x 65 columns]

In [ ]:
print(df.shape)

(1797, 65)

In [ ]:
print(df.columns[:-1])

Index(['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4',
       'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1',
       'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6',
       'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3',
       'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0',
       'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5',
       'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2',
       'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7',
       'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4',
       'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', 'pixel_6_1',
       'pixel_6_2', 'pixel_6_3', 'pixel_6_4', 'pixel_6_5', 'pixel_6_6',
       'pixel_6_7', 'pixel_7_0', 'pixel_7_1', 'pixel_7_2', 'pixel_7_3',
       'pixel_7_4', 'pixel_7_5', 'pixel_7_6', 'pixel_7_7'],
      dtype='object')

In [ ]:
print(digits.target_names)

[0 1 2 3 4 5 6 7 8 9]

In [ ]:
x=df[digits.feature_names]
y=df['target']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

print('Train Size:',x_train.shape)
print('Test Size:',x_test.shape)

Train Size: (1437, 64)
Test Size: (360, 64)

In [ ]:
model=LogisticRegression(max_iter=200)
model.fit(x_train,y_train)

LogisticRegression(max_iter=200)

In [ ]:
y_pred=model.predict(x_test)
print('Accuracy :',accuracy_score(y_test,y_pred))

Accuracy : 0.9583333333333334

In [ ]:
y_pred=model.predict(x_test)
print('Confusion Matrix :',confusion_matrix(y_test,y_pred))

Confusion Matrix : [[35  0  1  0  0  0  0  0  0  0]
 [ 0 32  0  1  0  0  0  0  3  0]
 [ 0  0 35  0  0  0  0  0  0  0]
 [ 0  0  0 37  0  0  0  0  0  0]
 [ 0  0  0  0 36  0  0  0  0  0]
 [ 0  0  0  1  0 36  0  0  0  0]
 [ 0  0  0  0  0  0 35  0  1  0]
 [ 0  0  0  0  1  0  0 35  0  0]
 [ 0  4  0  0  0  1  0  0 30  0]
 [ 0  0  0  0  1  0  0  0  1 34]]

In [ ]:
y_pred=model.predict(x_test)
print('Classification Report :',classification_report(y_test,y_pred))

Classification Report :               precision    recall  f1-score   support

           0       1.00      0.97      0.99        36
           1       0.89      0.89      0.89        36
           2       0.97      1.00      0.99        35
           3       0.95      1.00      0.97        37
           4       0.95      1.00      0.97        36
           5       0.97      0.97      0.97        37
           6       1.00      0.97      0.99        36
           7       1.00      0.97      0.99        36
           8       0.86      0.86      0.86        35
           9       1.00      0.94      0.97        36

    accuracy                           0.96       360
   macro avg       0.96      0.96      0.96       360
weighted avg       0.96      0.96      0.96       360

In [ ]:
# Task 2

import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
df=sns.load_dataset('titanic')

In [ ]:
print(df.shape)

(891, 15)

In [ ]:
print(df.dtypes)

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [ ]:
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df['age'].fillna(df['age'].median(),inplace=True)
df['embarked'].fillna(df['embarked'].mode()[0],inplace=True)
df['embark_town'].fillna(df['embark_town'].mode()[0],inplace=True)

/tmp/ipykernel_1501/2530115042.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(),inplace=True)
/tmp/ipykernel_1501/2530115042.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['embarked'].fillna(df['embarked'].mode()[0],inplace=True)
/tmp/ipykernel_1501/2530115042.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['embark_town'].fillna(df['embark_town'].mode()[0],inplace=True)

In [ ]:
df.drop('deck',axis=1,inplace=True)

In [ ]:
print(df.isnull().sum())

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [ ]:
df=pd.get_dummies(df,columns=['sex','embarked'],drop_first=True)

In [ ]:
x=df[['pclass','age','sibsp','parch','fare','sex_male','embarked_Q','embarked_S']]
y=df['survived']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

print('Train Size:',x_train.shape)
print('Test Size:',x_test.shape)

Train Size: (712, 8)
Test Size: (179, 8)

In [ ]:
model=LogisticRegression(max_iter=200)
model.fit(x_train,y_train)

LogisticRegression(max_iter=200)

In [ ]:
y_pred=model.predict(x_test)
print('Accuracy :',accuracy_score(y_test,y_pred))

Accuracy : 0.8044692737430168

In [ ]:
y_pred=model.predict(x_test)
print('Confusion Matrix :',confusion_matrix(y_test,y_pred))

Confusion Matrix : [[98 12]
 [23 46]]

In [ ]:
y_pred=model.predict(x_test)
print('Classification Report :',classification_report(y_test,y_pred))

Classification Report :               precision    recall  f1-score   support

           0       0.81      0.89      0.85       110
           1       0.79      0.67      0.72        69

    accuracy                           0.80       179
   macro avg       0.80      0.78      0.79       179
weighted avg       0.80      0.80      0.80       179